application: lti-gae-python
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /_ah/admin.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /ltiadmin.*
  script: imslti/admin/ltiadmin.py
  login: admin

- url: /request.*
  script: imslti/admin/request.py
  login: required

- url: /wiscrowd.*
  script: wiscrowd/wiscrowd.py

- url: /mod/.*
  script: mod/index.py

- url: /.*
  script: index.py

